# Generated by Django 4.0.8 on 2023-02-23 09:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial_locales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='body',
            field=wagtail.fields.StreamField([('one_column_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock())]))])), ('three_column_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))])), ('card_layout_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))]))], blank=True, use_json_field=None),
        ),
    ]
