# Generated by Django 4.0.8 on 2023-02-23 15:45

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_flatpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='body',
            field=wagtail.fields.StreamField([('one_column_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock())]))])), ('three_column_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))])), ('card_layout_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))])), ('speaker_layout_block', wagtail.blocks.StructBlock([('speakers', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('name', wagtail.blocks.CharBlock()), ('designation', wagtail.blocks.RichTextBlock()), ('social_links', wagtail.blocks.StructBlock([('social_network', wagtail.blocks.CharBlock()), ('profile_link', wagtail.blocks.CharBlock())])), ('biography', wagtail.blocks.RichTextBlock())])))]))], blank=True, use_json_field=None),
        ),
    ]
