# Generated by Django 4.0.8 on 2023-02-23 17:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_flatpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='body',
            field=wagtail.fields.StreamField([('one_column_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True)), ('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock())]))])), ('one_column_texte_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('paragraph', wagtail.blocks.RichTextBlock())]))])), ('three_column_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))])), ('card_layout_block', wagtail.blocks.StructBlock([('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))])), ('cfp_card_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True)), ('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title')), ('learn_more_url', wagtail.blocks.PageChooserBlock(label='Page Link')), ('description', wagtail.blocks.RichTextBlock(label='Description'))]))]))]))], blank=True, use_json_field=None),
        ),
    ]
