# Generated by Django 4.0.8 on 2023-03-01 10:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0008_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWithSidebar',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sidebar', wagtail.fields.StreamField([('sidebar_layout', wagtail.blocks.StructBlock([('sidebar', wagtail.blocks.StreamBlock([('block', wagtail.blocks.PageChooserBlock(label='Page Link'))]))]))], blank=True, use_json_field=None)),
                ('body', wagtail.fields.StreamField([('paragraph_layout', wagtail.blocks.StructBlock([('self_class', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))])), ('button', wagtail.blocks.StructBlock([('self_class', wagtail.blocks.CharBlock(required=False)), ('button_type', wagtail.blocks.CharBlock(help_text='btn__primary or btn__secondary')), ('button_url', wagtail.blocks.CharBlock()), ('button_title', wagtail.blocks.CharBlock())]))], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
