# Generated by Django 4.0.8 on 2023-03-01 14:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0010_sidebarpagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('agenda_layout', wagtail.blocks.StructBlock([('agenda', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('session', wagtail.blocks.RichTextBlock(label='Session title', required=False)), ('program', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('time', wagtail.blocks.CharBlock(required=False)), ('title', wagtail.blocks.RichTextBlock()), ('description', wagtail.blocks.RichTextBlock(required=False)), ('speakers', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.CharBlock(required=False)), ('designation', wagtail.blocks.CharBlock(required=False))])))])))])))])))])), ('paragraph_layout', wagtail.blocks.StructBlock([('self_class', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.StreamBlock([('block', wagtail.blocks.RichTextBlock())]))]))], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
